export const MESSAGES: Record<string, string> = {
  'MSG-LOGIN-INFO-ERROR': 'MSG-LOGIN-INFO-ERROR',
  'MSG-LOGIN-INFO-NOT-ACTIVE': 'MSG-LOGIN-INFO-NOT-ACTIVE',
  'MSG-LOGIN-INTERNAL-ERROR': 'MSG-LOGIN-INTERNAL-ERROR',
  'MSG-NO-MATCHING-RESULT': 'MSG-NO-MATCHING-RESULT',
}
